### ISSUE TITLE
Cannot find module 'web-oidc/remix' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by moishinetzer** [sergiodxa/web-oidc#44]
My project is not in esm, would that affect this? The types aren't being detected.

I.e. I have a basic remix project, I use the `import` syntax but I don't have `type: "module"` in my `package.json`.

Node v20.5.1

**Comment by sergiodxa** [comment]
Check in your tsconfig.json that you have moduleResolution set as Bundler, this is going to be the default value starting Remix v2.

https://github.com/remix-run/remix/blob/3e36c8dd8345e9896b91c48382501bf1380613f3/templates/remix/tsconfig.json#L8

**Comment by keul** [comment]
I had also to add this package to the `serverDependenciesToBundle` remix configuration

**Comment by sergiodxa** [comment]
@keul you can also set [serverModuleFormat](https://remix.run/docs/en/main/pages/v2#servermoduleformat) to `esm`, which will be the default starting Remix v2, but then you will need to add to `serverDependenciesToBundle` every CJS dependency.
