### ISSUE TITLE
Support PKCE Code Verification

### ISSUE THREAD

**Issue by bruceharrison1984** [sergiodxa/web-oidc#96]
Currently PKCE isn't implemented, so no `code_challenge` nor `code_challenge_method` is sent during the initial Authorization handshake. 

This breaks any applications that expressly require PKCE in order to authenticate.

**Comment by sergiodxa** [comment]
You can see in the OIDCStrategy for Remix that it's implemented

Here it's generated when starting the auth process https://github.com/sergiodxa/web-oidc/blob/ec9c0673aa19a0d4554fe2386a12f04821138251/src/remix.ts#L64-L88

And here it's used on the callback https://github.com/sergiodxa/web-oidc/blob/ec9c0673aa19a0d4554fe2386a12f04821138251/src/remix.ts#L104-L114

**Comment by bruceharrison1984** [comment]
Ah, you are correct. I was looking at query params instead of cookies, which obviously won't work for a SSR application. Thanks!
